Repository mattstratton/castanet, pull requests merged in 2020-12, with the labels that each got.

#309 Add Functionality: Show next upcoming episode
  .nvmrc
  REFERENCE.md
  exampleSite/config.toml
  gulp/tasks/dev/sass.js
  layouts/partials/grid.html
  layouts/partials/row.html
  package-lock.json
  package.json
  static/css/blue.css
  static/css/blue.css.map
  static/css/grey.css
  static/css/grey.css.map
  static/css/orange.css
  static/css/orange.css.map
  static/css/site.css
  static/css/site.css.map
  static/js/castanet-min.js
  static/js/castanet-min.js.map
  static/scss/custom.scss
Labels: enhancement

#321 Test with matrix build
  .github/workflows/ci.yml
  test/blue-grid.js
  test/blue-row-jumbo-false.js
  test/blue-row-jumbo-true.js
Labels: chore

#327 Update explicit tags for proper Apple/Google format
  REFERENCE.md
  exampleSite/content/episode/april.md
  exampleSite/content/episode/aug.md
  exampleSite/content/episode/dec.md
  layouts/section/episode.rss.xml
Labels: bug

#322 Add episode numbers/prefix in RSS and Relevant Titles/Links [Attempt #2]
  REFERENCE.md
  exampleSite/config.toml
  exampleSite/content/episode/aug.md
  layouts/episode/single.html
  layouts/guest/single.html
  layouts/host/single.html
  layouts/partials/grid-taxonomy.html
  layouts/partials/grid-upcoming.html
  layouts/partials/grid.html
  layouts/partials/row-taxonomy.html
  layouts/partials/row-upcoming.html
  layouts/partials/row.html
  layouts/section/episode.rss.xml
Labels: enhancement
